/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-04-19 00:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk&sensor=false\">\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("    function GetLoginDetails() {\r\n");
      out.write("        //var uri = 'http://localhost:58479/api/TrackOrder/Get';\r\n");
      out.write("        var uri = 'https://trackmyproductservice.azurewebsites.net/api/TrackOrder/Get';\r\n");
      out.write("        //var userID = sessionStorage.getItem(\"userID\");\r\n");
      out.write("        //Need to change this\r\n");
      out.write("        var userID = 1;\r\n");
      out.write("        var markers;\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            url: uri,\r\n");
      out.write("            ContentType: \"application/x-www-form-urlencoded\",\r\n");
      out.write("            data: { \"key\": userID },\r\n");
      out.write("            dataType: 'json',\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("\r\n");
      out.write("                markers = data;\r\n");
      out.write("                var mapOptions = {\r\n");
      out.write("                    //center: new google.maps.LatLng(markers[0].Latitude, markers[0].Longitude),\r\n");
      out.write("                    center: new google.maps.LatLng(53.328430, -6.304864),\r\n");
      out.write("                    zoom: 5,\r\n");
      out.write("                    mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var infoWindow = new google.maps.InfoWindow();\r\n");
      out.write("                var map = new google.maps.Map(document.getElementById(\"map_canvas\"), mapOptions);\r\n");
      out.write("                for (i = 0; i < markers.length; i++) {\r\n");
      out.write("                    var data = markers[i]\r\n");
      out.write("                    //var myLatlng = new google.maps.LatLng(data.Latitude, data.Longitude);\r\n");
      out.write("                    var myLatlng = new google.maps.LatLng( 53.328430, -6.304864);\r\n");
      out.write("                   \r\n");
      out.write("                    var marker = new google.maps.Marker({\r\n");
      out.write("                        position: myLatlng,\r\n");
      out.write("                        map: map,\r\n");
      out.write("                        //title: \"Order: \"+data.OrderName +\" | \"+ data.VehicleDetails\r\n");
      out.write("                        title: \"Order: \"+ \"AppleiPhone 7\" +\" | \"+ \"Vehicle: Volkswagan, Number:IRL 05-D-12365', 1)\"\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("                (function (marker, data) {\r\n");
      out.write("                    google.maps.event.addListener(marker, \"click\", function (e) {\r\n");
      out.write("                        infoWindow.setContent(data.TrackingID);\r\n");
      out.write("                        infoWindow.open(map, marker);\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                })(marker, data);;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"map_canvas\" style=\"width: 500px; height: 400px\"></div>\r\n");
      out.write("<input type=\"button\" value=\"click here\"  onclick=\"GetLoginDetails()\"/>\r\n");
      out.write("<p>Use this area to provide additional information.</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/about.jsp(9,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.1.10.2.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
